services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress_data:/var/www/html
    networks:
      - dev_network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - dev_network

  webserver:
    image: nginx:latest
    ports:
      - "5500:80"
    volumes:
      - ./lorem.html:/usr/share/nginx/html/index.html:ro
    restart: always
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge

volumes:
  wordpress_data:
  db_data:
